// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function MediaProxyMiddleware() {
  return window['go']['main']['App']['MediaProxyMiddleware']();
}

export function StartRemoveBackground(arg1, arg2) {
  return window['go']['main']['App']['StartRemoveBackground'](arg1, arg2);
}
